import Head from 'next/head';

import { useCryptoSelections } from '@/hooks/useCryptoSelections';

import styles from '../styles/Home.module.css';

import type { NextPage } from 'next';

const Home: NextPage = () => {
  const { selectedCoins, toggleSelectedCoins, btcPrice1, ethPrice1 } =
    useCryptoSelections();

  console.log(selectedCoins);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>ビットコイン</h1>
        <p onClick={() => toggleSelectedCoins('bitcoin')}>選択</p>

        <p className={styles.description}>価格: {btcPrice1} 円</p>

        <h1 className={styles.title}>イーサリアム価格</h1>

        <p className={styles.description}>価格:{ethPrice1} 円</p>
      </main>
    </div>
  );
};

export default Home;
